### PR TITLE
Add autocomplete text field for device selection

### PR DESCRIPTION
**Pull request by arthurmcgregor**
For device selection, I've added a new text field which has autocomplete enabled called 'filter'. As you type it will show a list of devices. When you click on the device you want, it will clear the autocomplete box and change the device select to that device.

I have kept the select dropdown in addition to the new text field because newbies like me won't know device names so won't know what to type. In addition, it was an easy way to store and return the device id which is needed for the query.

Something to consider is only displaying the filter field when there is (say) 10 or more devices. This means it will only be shown for users who would actually benefit from it being there.

device_autocomplete

References #81

### CODE REVIEW

**Comment by mjs** [comment]
Thanks for this.

I'm not too keen on 2 fields for doing the same thing. That seems pretty confusing for me. Could the dropdown appear - showing all available devices - as soon as the field has focus? This would aid discoverability when the user isn't sure of the device name. Is the dropdown element scrollable?

**Comment by arthurmcgregor** [comment]
How about something like this? (In terms of functionality at least)
https://semantic-ui.com/modules/dropdown.html#multiple-search-selection

We could include device groups as well (with an icon to distinguish from devices)

**Comment by mjs** [comment]
Perfect. That looks really nice. Being able to select multiple devices and/or groups would be nice extra.

**Comment by arthurmcgregor** [comment]
OK I'll look into it....

**Pull request closed without merging**
